# Generated by Django 4.2.9 on 2024-02-06 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', help_text='This form will be available to users only when status is active and the current date is between the start and end dates.', max_length=10),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='seq_no',
            field=models.IntegerField(default=0, help_text='Order of the questions.', verbose_name='Order No.'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='form_responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='form_creator.formresponder'),
        ),
        migrations.AlterUniqueTogether(
            name='formquestion',
            unique_together={('form', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='formresponder',
            unique_together={('form', 'user')},
        ),
    ]
