# Generated by Django 4.2.9 on 2024-02-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluconnect', '0002_event_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteeruser',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='volunteeruser',
            old_name='user_name',
            new_name='password',
        ),
    ]
