# Generated by Django 5.0.1 on 2024-02-04 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluconnect', '0002_rename_events_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteeruser',
            name='ats_status',
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ats_status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='ABSENT', max_length=7)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voluconnect.volunteeruser')),
                ('event_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voluconnect.event')),
            ],
        ),
    ]
