# Generated by Django 5.0.1 on 2024-02-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluconnect', '0003_remove_volunteeruser_ats_status_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
    ]
