# Generated by Django 5.0.1 on 2024-02-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluconnect', '0004_alter_volunteeruser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeruser',
            name='user_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='User Name'),
        ),
    ]
