# Generated by Django 5.0.1 on 2024-02-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluconnect', '0004_remove_event_attendees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='event_name',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attendee',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('event', 'user')},
        ),
    ]
