# Generated by Django 5.0.1 on 2024-02-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluconnect', '0005_rename_event_name_attendance_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_images/'),
        ),
    ]
