# Generated by Django 4.2.9 on 2024-02-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluconnect', '0005_field_form_fieldchoice_section_field_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldchoice',
            name='field',
        ),
        migrations.RemoveField(
            model_name='section',
            name='form',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
        migrations.DeleteModel(
            name='FieldChoice',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
