# Generated by Django 5.0.1 on 2024-02-07 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluconnect', '0006_attendance_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='image',
            new_name='qr_image_url',
        ),
    ]
