# Generated by Django 5.0.1 on 2024-02-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluconnect', '0007_rename_image_attendance_qr_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='qr_image_url',
        ),
        migrations.CreateModel(
            name='EventQrcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_image_url', models.ImageField(blank=True, null=True, upload_to='qr_images/')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voluconnect.event')),
            ],
        ),
    ]
