# Generated by Django 5.0.1 on 2024-02-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluconnect', '0008_remove_attendance_qr_image_url_eventqrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventqrcode',
            name='qr_image_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
