# Generated by Django 5.0.1 on 2024-02-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voluconnect', '0006_remove_fieldchoice_field_remove_section_form_and_more'),
        ('voluconnect', '0009_alter_eventqrcode_qr_image_url'),
    ]

    operations = [
    ]
